command_socket = "/var/run/sozu/socket"
saved_state    = "./state.json"
log_level      = "debug"
log_target     = "stdout"
command_buffer_size = 16384

[metrics]
address = "192.168.59.103"
port = 8125

[proxies]

[proxies.HTTP]
address = "0.0.0.0"
proxy_type = "HTTP"
max_connections = 20000
port = 80
buffer_size = 16384
worker_count = 1